
# Conclusiones

Esta tesis analizó, en población estudiantil, los factores asociados a las actitudes hacia la igualdad de derechos en tres dimensiones: entre hombres y mujeres, para grupos étnicos y para homosexuales. Desde la teoría de recursos y desde la hipótesis de las posiciones de desventaja, se esperaba que el poseer recursos socioeconómicos o culturales y el pertenecer a grupos en desventaja fomente una actitud positiva hacia la igualdad de derechos hacia distintos grupos. Asimismo, en base a estudios sobre formación ciudadana se esperaba que características y prácticas de la escuela, como las relaciones con los profesores y la composición de las aulas influyeran en las actitudes hacia la igualdad de derechos. Basándose en ambas líneas de investigación, esta tesis se propuso indagar en si características de la escuela, como espacio fundamental de socialización, pueden disminuir el efecto de las características individuales sobre las actitudes hacia igualdad de derechos. Dicho de otro modo, esta tesis propone que un clima escolar donde se dan buenas relaciones interpersonales entre los profesores y/o estudiantes puede hacer que estudiantes de sexo masculino o con bajos niveles de conocimiento cívico posean igualmente buenas actitudes hacia la igualdad de derechos. 

En primer lugar, los resultados nos permiten comprobar parcialmente el efecto de las características individuales. A partir del modelo multinivel, se evidencia que los recursos socioeconómicos afectan parcialmente las actitudes a la igualdad de derechos. Ninguno de los recursos analizados afecta de forma relevante y consistente las actitudes hacia la igualdad de derechos para homosexuales. No obstante, tanto la cantidad de libros en el hogar como la educación de los padres se relacionan positivamente con las actitudes hacia la igualdad de derechos entre hombres y mujeres y para grupos étnicos. En relación con la hipótesis de la posición de desventaja, es posible afirmar que pertenecer al sexo femenino se asocia positivamente con las actitudes hacia la igualdad de derechos en las tres dimensiones en estudio (y especialmente en lo relativo a los homosexuales), mientras que los antecedentes migratorios no se relacionan significativamente con estas actitudes de los jóvenes y la pertenencia a un grupo étnico sólo afecta las actitudes hacia la igualdad de derechos para grupos étnicos. El conocimiento cívico demostró tener un considerable efecto sobre las actitudes hacia la igualdad de derechos.  

En segundo lugar, los análisis nos entregan información sobre el efecto de las características y prácticas de la escuela. De modo contrario a lo hipotetizado, las características de composición del aula analizadas no poseen un efecto relevante para explicar las actitudes hacia la igualdad de derechos, así como la apertura a la discusión en el aula tampoco presenta un efecto consistente en estas actitudes, asociándose positivamente sólo a las actitudes hacia la igualdad de derechos entre hombres y mujeres. Asimismo, en relación con el clima en el aula, las dimensiones de “relaciones interpersonales entre estudiantes” y de “situaciones de violencia en la escuela” no afectan significativamente las actitudes de los jóvenes hacia la igualdad de derechos en los tres factores analizados. Sin embargo, acorde a lo esperado, se pudo evidenciar un efecto positivo de las relaciones interpersonales entre estudiantes y profesores en las actitudes hacia la igualdad de derechos para dos de las tres dimensiones analizadas. De modo que, si un profesor desarrolla buenas relaciones con sus estudiantes estos tendrán más probabilidades de poseer actitudes favorables hacia la igualdad de derechos entre hombres y mujeres y para grupos étnicos.  

En tercer lugar, los resultados dan luces sobre la hipótesis central de la tesis, que proponía que prácticas de la escuela podrían moderar las diferencias en las actitudes sobre la igualdad de derechos producidas por características individuales. A partir de la interacción multinivel se puede evidenciar que mejores relaciones con los profesores disminuyen las diferencias basadas tanto en el sexo como en el desigual conocimiento cívico de los estudiantes en dos de las tres dimensiones analizadas. Más específicamente, las buenas relaciones con el profesor en el aula son capaces de moderar o disminuir las diferencias tanto en las actitudes hacia la igualdad de derechos entre hombres y mujeres como en las actitudes hacia la igualdad de derechos para grupos étnicos. Sin embargo, pese a encontrar estos efectos significativos, es importante señalar que incluir estos efectos de moderación en los modelos aumenta levemente la capacidad explicativa de los mismos. Es decir, aunque este rasgo de la escuela es capaz de moderar las diferencias individuales señaladas, esta moderación es más bien leve y por ello estas conclusiones deben ser tomadas con precaución.

## Discusión

En términos teóricos, sobre el efecto de las características de las escuelas, esta investigación nos entrega información importante respecto a los efectos. Desde la teoría del contacto intergrupal destacada por Allport (1954) y la teoría del “efecto de los compañeros” (Bellei, 2013) se esperaba un efecto relevante por los factores de composición. Más específicamente se esperaba, basados en las investigaciones de Caro y Schulz (2012); y de Isaac, Moslawski y Van der Werdf (2012), que la mayor presencia en el aula de personas pertenecientes a grupos desventajados fomentara actitudes más favorables a la igualdad de derechos. No obstante, en el caso de este estudio no ha sido posible encontrar esta asociación al considerar además otros factores influyentes, como el clima escolar, la apertura a la discusión en el aula y características individuales. Una pregunta interesante para indagar en otros estudios puede relacionarse con por qué en este contexto no se encuentra la relación esperada. Una posibilidad por estudiar refiere a las relaciones entre los estudiantes en contextos con más variedad de composición dentro del aula.

Sin duda, la conclusión más relevante de esta investigación versa sobre el rol que cumple el clima escolar por sí mismo y moderando las diferencias entre estudiantes sobre dos dimensiones de las actitudes hacia la igualdad de derechos. Siguiendo la evidencia levantada por tanto por Caro y Schulz (2012), como por Schulz y Ainley (2018) se esperaba un relevante efecto del clima escolar en las actitudes hacia la igualdad de derechos. Basados en esta premisa, la presente investigación diferenció las relaciones con el profesor de las relaciones entre estudiantes. Al diferenciar los efectos del clima del aula en tres dimensiones se pudo observar que buena parte del efecto del clima del aula se debe en particular a la relación que poseen los estudiantes con los profesores. El rol del trato con los profesores en la formación de las actitudes a la igualdad de derechos puede comprenderse como un efecto de socialización donde prima el comportamiento de figuras referentes de autoridad, como los docentes, frente a la relación entre los estudiantes.

En términos de política pública esto releva la importancia de fomentar una formación integral de los profesores, preparándolos no solo para enseñar sus respectivas asignaturas sino, también, para dotarlos con herramientas socioemocionales para mantener un buen trato y buenas relaciones con los estudiantes. Esto es relevante ya que el ejemplo del profesor parece especialmente importante en la formación de actitudes hacia la igualdad de derechos.

La apertura a la discusión en el aula, destacada por Barber, Torney-Purta y Fennelly (2010) no presentó efectos significativos al ser controlada por las otras variables de nivel individual y escolar. Una posible razón para esto es que el efecto positivo de la discusión en el aula se deba en realidad al efecto positivo que tiene esta práctica en las relaciones entre estudiantes y profesores, por lo que no es posible visualizar el efecto de la apertura a la discusión en el aula cuando se controla por las relaciones interpersonales con los docentes. Sería interesante poder indagar en la posible relación de mediación entre estas variables en próximas investigaciones. 

Finalmente, me gustaría destacar dos elementos. En primer lugar, considero fundamental relevar que, contrario a lo esperado, en consideración de los resultados de esta investigación es posible proponer que las actitudes hacia la igualdad de derechos para homosexuales siguen una dinámica relativamente distinta a las otras dos dimensiones de las actitudes hacia la igualdad de derechos. Entre las variables independientes analizadas, es una cantidad menor las que tienen un efecto significativo en este tipo de actitudes (en comparación a las otras dos dimensiones analizadas) y las pendientes de estos efectos no varían entre escuelas, por lo que no fue posible indagar en características y prácticas de la escuela que podrían afectar la relación entre características individuales y las actitudes hacia la igualdad de derechos para homosexuales. En este sentido, los resultados parecen indicar que sería más apropiado analizar en detalle específicamente los factores que influyen en este tipo de actitudes y, a partir de ello, indagar en los posibles efectos de interacción. En segundo lugar, esta investigación proponía en sus bases que comprender cómo características y prácticas de las escuelas pueden moderar las diferentes actitudes de los estudiantes hacia la igualdad de derechos para grupos desfavorecidos es un elemento fundamental por investigar para retroalimentar las políticas públicas en formación ciudadana. En consideración de que la evidencia indica que existen características individuales que afectan estas actitudes y, dado que no podemos cambiar estas características, se vuelve fundamental transformar las escuelas en un espacio que permita que estas características sean menos relevantes en el desarrollo de actitudes favorables hacia la igualdad de derechos. Si bien esta investigación sólo logró identificar una práctica de las escuelas que permite disminuir las diferencias en estas actitudes, se constituye como un hallazgo relevante y esperanzador el hecho mismo de haber identificado esta práctica. En otras palabras, la posibilidad de fomentar una actitud favorable hacia la igualdad de derechos en distintos grupos mediante practicas escolares es una excelente noticia para un panorama latinoamericano donde priman las desigualdades sociales y donde es especialmente necesario fomentar políticas que permitan promover la igualdad, el respeto y el reconocimiento mutuo.