---
title: '<span style="color: #8149AB;"> ¿Qué pueden hacer las escuelas para promover actitudes positivas hacia la igualdad de derechos? Las buenas relaciones entre profesores y estudiantes como una oportunidad para disminuir las diferencias en estas actitudes'
subtitle: "Tesis para optar al grado de Socióloga y Magíster en Ciencias Sociales"
author: "Anais Herrera Leighton"
date: "Santiago de Chile, 2023" # o para fecha actual: "`r Sys.Date()`"
institution: "Universidad de Chile"
degree: "Tesis para optar al grado de Socióloga y Magíster en Ciencias Sociales"
advisor: "Profesor guía: Juan Carlos Castillo"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 12pt
lof: True
lot: True
---

# Resumen {-}

En un mundo con altos niveles de desigualdad y crecientes expresiones de intolerancia, se hace fundamental la aprobación de políticas públicas que avancen a garantizar la igualdad de derechos. En sociedades democráticas la promoción de estas políticas depende en parte importante de la opinión de la ciudadanía. Uno de los principales espacios en los que el Estado puede intervenir para promover actitudes positivas hacia la igualdad de derechos es la escuela, por su rol fundamental en la socialización de principios y valores. Diversas investigaciones han indagado en los factores asociados a las actitudes hacia la igualdad de derechos de los jóvenes en edad escolar, orientándose en dos líneas: una relacionada con características y experiencias individuales de los estudiantes, y otra enfocada en características y prácticas de la escuela a la que asisten. La presente investigación pretende aportar a estas líneas de estudio incorporando ambas teorías en un modelo estadístico para evaluar si alguna de las características de la escuela (señaladas frecuentemente en investigaciones anteriores) posee la capacidad de disminuir las diferencias individuales en las actitudes hacia la igualdad de derechos. Para ello se estiman regresiones multinivel utilizando datos del Estudio Internacional sobre Educación Cívica y Ciudadana (ICCS) 2016 de 3.920 estudiantes de 8°básico de 166 escuelas chilenas. Los resultados indican que las buenas relaciones entre estudiantes y profesores son capaces de disminuir el efecto del sexo y el nivel de conocimiento cívico en dos de las tres dimensiones de las actitudes hacia la igualdad de derechas analizadas en el estudio.

**Palabras clave:** *“formación ciudadana”*, *“educación cívica”*, *“igualdad de derechos”*, *"clima escolar"*, *“jóvenes”*. 
